# Stage 1: Installer for AWS CLI, Snyk, and kubectl
FROM amazonlinux:2 as installer
USER root
# Install AWS CLI, Snyk, and kubectl
RUN yum update -y \
    && yum install -y unzip curl \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install --bin-dir /aws-cli-bin/ \
    && mkdir /snyk && cd /snyk \
    && curl https://static.snyk.io/cli/v1.666.0/snyk-linux -o snyk \
    && chmod +x ./snyk \
    && curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl  # Ensure kubectl is in the right place

# Stage 2: Jenkins Agent Base
FROM jenkins/inbound-agent:4.10-3-jdk11

# Switch to root user for directory creation and copying files


# Copy over AWS CLI, Snyk, and kubectl from the installer stage
COPY --from=installer /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=installer /aws-cli-bin/ /usr/local/bin/
COPY --from=installer /snyk/ /usr/local/bin/
COPY --from=installer /usr/local/bin/kubectl /usr/local/bin/

# Create necessary directories with root privileges
RUN mkdir -p /k8s/jenkins

# Copy agent.jar to the expected location
COPY agent.jar /usr/share/jenkins/agent.jar

# Install Python for custom builds
RUN apt-get update && apt-get install -y python3 python3-pip

# Switch back to Jenkins user
USER jenkins

# Entrypoint to automatically start the JNLP agent
ENTRYPOINT ["/usr/local/bin/jenkins-agent"]
